### PR TITLE
Changed wording of requirements for members to use names

### PR DESCRIPTION
**Pull request by jamesfowkes**
membership-of-the-hackspace.rst - I removed the word "legal" from "legal name", since the Companies Act doesn't use the term "legal name", just "name" for the register of members (as far as I can tell).

storage-in-the-hackspace.rst - changed "full name" to "identifiable name". Also, made it that the optional email address was about communication, not identification.

### CODE REVIEW

**Comment by dpslwk** [comment]
For storage purposes identifiable name was something we where trying to avoid by specially asking for a full name. As identifiable name is too open to interpretation by members and leaves it impossible to track down owners. 
You might of example thing the "James" is a perfectly identifiable name for your stuff, un aware that we have 7 Current members and 13 Ex members, all who might have left stuff around the place as just labeled "James" 
(I'm extending here the requirement for name on 35lt storage to stuff on LPS and DNH around the space)

**Comment by jamesfowkes** [comment]
I added the word "uniquely" in there to make it clear that the name on storage box needs to identify someone uniquely.

**Comment by jamesfowkes** [comment]
Haven't heard anything about this pull request, are there any problems with it?

**Comment by geeksareforlife** [comment]
Nope

We have only been merging the little things during the consultation, to
make sure that things aren't changing whilst people are reading.

Consultation ends tomorrow, so the trustees will be looking at all of these
and sorting them all out

**Pull request closed without merging**
