### PR TITLE
Rtd draft

### PR DESCRIPTION
**Pull request by ocatelle**
Told you so @dpslwk :P

### CODE REVIEW

**Comment by geeksareforlife** [comment]
Have we removed the Lone Worker alarm from the space?  If so, this looks good to me.

We probably need to have a conversation about lone workers in the future though!

**Comment by ocatelle** [comment]
Yeah, it was removed sometime last year (not sure exactly when other than before October 5th as that's as far back as the slack records go) after a large number of false alarms and little known use of the system. It's currently sat on a shelf in Members Storage awaiting disposal. A replacement system is on the safety team to-do list, and is definitely a discussion we should have at some point.

**Comment by geeksareforlife** [comment]
@dpslwk I don't think we need this branch anymore?

**Comment by dpslwk** [comment]
we do as it where incoming changes can be merged so they can be review by looking at https://rules.nottinghack.org.uk/en/rtd-draft/

**Pull request merged**
