### PR TITLE
Storage in the Hackspace

### PR DESCRIPTION
**Pull request by sid351**
Mainly added some words to indicate a member should be making a minimum monthly commitment to the space in order to have a box.

### CODE REVIEW

**Comment by rlp10** [comment]
As I understand it Sid, mimimum payment to the Space is a hot debate which both members and trustees have strong feelings on. By creating a minimum payment, there would effectively be two tiers of members: one entitled to storage and the other not. As I understand it the issue is dealt with informally currently - the trustees "have a word" with anyone they think is unfairly taking advantage of the space's resources whilst paying very little.

I don't understand the current wording. Am I right in thinking that it calls for a minimum, but doesn't say what the minimum is?

I don't know whether the issue of minimum payment is something that the trustees intend us to tackle as part of the consultation.

Trustees - can you give us some feedback? Are you happy for there to be a debate here on minimum payment or is that topic off the table?

**Comment by geeksareforlife** [comment]
Nothing is off the table, but I personally would be against a minimum

**Comment by dpslwk** [comment]
Owens's rewrites #11 & #6 for a minimum membership fee for storage are something we (the trustees) had worked to remove from the rules, 
A minimum for storage was in the original rules but has not been enforced for ages, 
Minimum indicates tired membership which is defiantly something we do not want
Give the core parts of membership requirements no minimum should be need to be defined and members should take there storage needs into account when deciding there payment amount.

Personally I'm against a minimum for storage.

'RepRap' Matt

**Comment by sid351** [comment]
I tried to word it in a way to say that people should be expected to
contribute a minimum to the space, such as their time and effort on a team,
or teams, OR a suitable payment in lieu of that.

I don't think it's fair for some people to put in significantly less to the
space and have access things that are at a premium in the space (such as
storage).

Also the YouTube tour says it's a minimum £10 per month have a box, so that
probably needs updating, as that was the impression I was under.

I know having a minimum payment isn't something the space wants to do (and
would make differences with tax) but i think it's fair and reasonable to
point out people are expected to contribute something (time, effort, things
or money) in order to access certain things.

Such as the laser and having to pay for your running time on it separately
to your monthly payment (which I'm all favour and am not complaining
about). Obviously it's easier to see the extra cost associated with the
running the laser, but it's still a form of tiered access.

**Comment by dpslwk** [comment]
The hackspace has never accepted anything in lieu of money for membership.
First it's impossible to quantify anything other than money.
Second it's completely unfair to members that do already contribute huge amounts of time and effort but don't do it in lieu of there regular membership payment.  
Without membership payments we would not exist.

'RepRap' Matt

**Comment by sid351** [comment]
Ok.  I don't think I've communicated what I was thinking clearly, as I
didn't mean to suggest that people could choose to pay nothing all.

I'll have a think and try again.

**Comment by drazziweht** [comment]
We have a charge for the Laser Per Hour separate to the membership fee. This makes sense because the laser is a finite resource and has an incremental per use cost.

Why should we not have a charge for additional personal storage separate to the membership fee. Storage space like the laser is a finite resource with a real cost although perhaps not quite so direct/incremental as the laser cost.

Say £X / Month per 35L Box rental.

I'm actually not sure I'm really in favour of this, but its maybe a possibility.

**Comment by geeksareforlife** [comment]
you make a good point, and to be honest my only response would be along the lines of "we have always..."

Having a storage box is a privilege, and we wouldn't want people paying penny a month to have a box I suppose.  Working it as a payment for a box sounds a lot better than having a minimum as well.  I would want that bar to be suitably low though - no more than £5 a month for a box space.

If we are going to have that, it should able be a sliding scale - if you want two boxes, the second is more expensive.  A third should be fairly prohibitively expensive.

The problem is that Large Project Storage (LPS) is free. If boxes are going to cost, LPS will need additional rules around what should and shouldn't be on there.

**Comment by drazziweht** [comment]
From occasional casual reading of the london hackspace list they seem to have a "bid for storage" sort of system where if a member wants to have some large project storage they ask the membership for permission to store X for Y days and it's approved or not.

Not sure exactly if it works just like that but it sounds like the basis for a reasonable solution to Large Project storage with a bit of thinking about the details.

**Comment by sid351** [comment]
I think large storage should work as an extension of the box storage
situation that we come up with (if any).

Ultimately the problem will be 'policing' any situation.

I still think it's fair to expect members to contribute a little bit more
for access to the things that come as a premium to the space.  I also don't
think that the additional contribution should have to always be monetary,
but that just gets harder to monitor and police.

**Comment by sid351** [comment]
Hopefully my latest commit explains what I was thinking a bit more clearly.

**Pull request closed without merging**
