### PR TITLE
Delete entire rule "Abiding by UK Law"

### PR DESCRIPTION
**Pull request by drazziweht**
A rule that states "You must abide by UK law in the space" is a void rule as it does not in any way change any activity in the space that is within the law or allowed by the rules.

All UK Laws are active within the space with or without such a rule and hence the rule is of no effect and is therefore pointless.

Why would we have an additional pointless rule ?

For avoidance of doubt and to ease fears that removing this rule might restrict the ability of the trustees to enforce illegal activity in the space which is not explicitly prohibited by the rules the "respect the space" rule is updated to add a requirement to abide by UK law in the space.

### CODE REVIEW

**Comment by rlp10** [comment]
As a technical point, the effect of the rule is that breaches of UK law will be enforced by the Trustees, which would not be the case otherwise. It isn't correct to say that the rule does nothing. For example, under the rule, I can bring a complaint that another person has broken the law and the Trustees would be required to consider investigating the person, whereas otherwise they may not - they could just refer me to the police/courts.

It does seem to me however that this is a problematic area requiring careful thought. If the Trustees investigate a crime then they may be accused of contaminating a potential future police investigation. This is a very real problem and one that I have dealt with in the past.

I'm going to have a think about this one.

**Comment by geeksareforlife** [comment]
Illegal activities (yes, plural)  already happen in the space and at the
moment the only recourse the trustees have is to call the police in the
case of criminal breaches, or raise a civil suit for other cases.

**Comment by rlp10** [comment]
James, I presume you say it is the only recourse because illegal activities in themselves are not currently a breach of the rules (unless they also happen to breach another rule)?

**Comment by drazziweht** [comment]
"As a technical point, the effect of the rule is that breaches of UK law will be enforced by the Trustees, which would not be the case otherwise"

If this is the reason for the rule I think it fails

There is nothing as far as I can see that REQUIRES the trustees to enforce rules, hence with or without this rule the trustees are able to ignore breaches of the law in the space in the same way as other members are, or to enforce them as a citizen, or report them to a constable for investigation / enforcement, i.e. absent something which puts a legal duty on the trustees to enforce hackspace rules which is not covered by the legal requirements of citizens to enforce UK laws I can see no real status change made by this rule (not I may be wrong here, I am not a lawyer and have no legal training!!)

I can actually think of no law that could be broken in the space that would not allow the trustees the ability to enforce under at least the spirit of "Be Excellent" or "Respect the Hackspace" rules.

**Comment by drazziweht** [comment]
"Illegal activities (yes, plural)  already happen in the space and at the
moment the only recourse the trustees have is to call the police in the
case of criminal breaches, or raise a civil suit for other cases."

This is NOT the case.
The trustees currently have the power under the Grievance procedure https://wiki.nottinghack.org.uk/wiki/Grievance_Procedure to take action up to an access ban.

Breaking the law in the space would seem to be covered by this policy and give the trustees the required powers of enforcement without additional rules.

**Comment by msemtd** [comment]
I think the rule is useful to reinforce the sentiment of "please don't do illegal stuff at the Hackspace - you put its existence in jeopardy"

**Comment by drazziweht** [comment]
_"I think the rule is useful to reinforce the sentiment of "please don't do illegal stuff at the Hackspace - you put its existence in jeopardy"_

We have rules "Be Excellent"  and "Respect the Hackspace"
an additional sentance in one of those rules clarifying that obeying the law is part of the remit would be more appropriate if people think it is required than an entirely separate "null rule"

**Comment by geeksareforlife** [comment]
Actually it is the case. The grievance procedure says it is for

"behaviour which has caused offence, harm or distress to another member or
members; or has threatened the safety of the Hackspace."

It would be a gross misuse of this currently to try and apply this to
activities that whilst illegal are not actively hurting others.

J

**Comment by geeksareforlife** [comment]
I'd also like to point out that in my time as a trustee I have had the
following conversation with three separate members:

Me: please don't do X in the space, it is illegal
Them: there is nothing in the rules about it!
Me: *facepalm*

**Comment by drazziweht** [comment]
"It would be a gross misuse of this currently to try and apply this to
activities that whilst illegal are not actively hurting others."

1. Could you give an example of something which is illegal but does not hurt others ?

2. Any breaking of the law in the space by a member put the space at risk of civil or criminal penalties and any person who is aware of the activity and does not report it at risk of aiding and abetting in the case of criminal law so I would say that it would definitely be covered by the grievance procedure as a risk to the space.

**Comment by geeksareforlife** [comment]
1. Torrenting copyrighted films. Other examples would make it obvious about
who I was talking about

2. Currently, I would not interpret the grievance procedure (that I wrote)
in that way

**Comment by drazziweht** [comment]
"1. Torrenting copyrighted films. Other examples would make it obvious about
who I was talking about

2. Currently, I would not interpret the grievance procedure (that I wrote)
in that way"

I think you should!!, Torrenting copyrighted films from the space puts the space (as the owner of the internet connection) at risk of civil penalties for copyright infringement, Since these penalties can be high it could even put the existence of the space at risk.

**Comment by geeksareforlife** [comment]
We had a quiet word and it stopped

**Comment by drazziweht** [comment]
Pressed the wrong button, did not intend to close

**Comment by rlp10** [comment]
I have sympathy with your *facepalm* story, James, but I do think that the trustees should be able to point to a specific rule which has been broken if they are going to take action against members.

That's the point of rules generally, so that one group (here the members) can understand their responsibilities towards another group (the space, represented by the trustees, and the other members). The "it's not in the rules" defence seems a pretty good one to me. I'm not commenting on the specific issue of copyright infringement, but just generally.

I suppose that's why I consider it important to carefully consider and improve the rules as much as possible.

**Pull request closed without merging**
