### PR TITLE
Update abiding-by-UK-law.rst - No Vaping

### PR DESCRIPTION
**Pull request by drazziweht**
Why the ban on Vaping ?, It seems a bit arbitrary, especially as "an extension to UK LAW",

Should we be expecting a "No Drugs, as per uk law, and no alcohol as an extension next ?"

Or Maybe a "No Noise nuisance in accord with UK law and a vow of silence while in the space as an extension ?"

### CODE REVIEW

**Comment by loriamor** [comment]
There are studies to see whether this is harmful in enclosed spaces. I haven't read any so I am not sure of the outcomes of them but just because it hasn't been proven to be harmful doesn't mean it isn't. On a personal note though... I don't like the way they smell and if I can smell them does this mean I am breathing in the fumes? I have nothing against the people who do this but I would rather it not be done inside. Maybe a ventilation system could be built if people find it necessary to vape inside. As it doesn't have the side effect of burning the place down I would have no problems with a 'vaping room'.

As an ex-smoker, I know how you feel but I also don't want to be breathing in nicotine again.

**Comment by drazziweht** [comment]
_"There are studies to see whether this is harmful in enclosed spaces. I haven't read any so I am not sure of the outcomes of them but just because it hasn't been proven to be harmful doesn't mean it isn't"_

Banning on the basis of "Has not been proven to be harmful but it might be" seems a step beyond reasonableness to me, and rules based on unreason invite poor adherence.

_"I don't like the way they smell and if I can smell them does this mean I am breathing in the fumes?"_

This is a better reason for a ban, personal preferences are important, and we live in a democracy. If the majority do not want vaping in the space then a ban would be a reasonable approach, but at present I have no idea what the general feeling is and if the proposed ban is based on feedback from a number of people or just 1 or 2 ? which is why I thought it worth raising for discussion.

**Comment by geeksareforlife** [comment]
With Wales banning indoor Vaping from 2017 and the World Health
Organisation also recommending complete indoor bans it seems like the way
to go.

I have had a few people talk to me as a trustee about it, but only a few.
That said, as we are British, the vast majority of people won't complain -
they will simply stop coming.

Alcohol is still legal in the UK, but we would act against anyone getting
paralytic in the space and causing issues with others. Drugs already done
under this rule as they are illegal.

On a personal note, I don't like Vaping around me either. People can claim
that the by product has nothing in it, but it smells so it must have
something in it. I personally don't want to take that risk.

**Comment by rlp10** [comment]
Lori, it seems to me that if there are studies to show passive vaping is harmful then that is very important to this discussion. Afterall, we are aiming to create a "safe space". Can you (or others who may support the ban on vaping) provide any references or links as firm evidence that it is harmful?

James, I wasn't familiar with the Welsh legislation or the WHO position and so I've read a BBC article: http://www.bbc.co.uk/news/uk-wales-33025872 I don't think that there is a the consensus that your post suggests. Apparently, there are significant groups opposed to the Welsh ban, including Cancer Research UK, The British Heart Foundation Wales and the UK Centre for Tobacco and Alcohol Studies. I think that this is a debate that is still being played out, rather than one that is settled.

A key motivation for the Welsh ban is the desire to reduce the exposure of e-cigarettes to children. That seems only tenuously relevant for us since so few children attend the Hackspace.

**Comment by geeksareforlife** [comment]
There is indeed a debate, but from what I've read it seems very much to me
along the lines of "Vaping is not as bad as smoking and will help people
give up smoking".

A recent study shows harmful effects:

http://www.theguardian.com/society/2015/feb/04/e-cigarettes-toxic-chemicals-research-finds-lung-damage

Nowhere near as bad as cigarettes, but there you go.

I'm in no way saying that the debate here, or in general is over, we put it
in the rules because a number of members expressed that they found it
horrible when in the space, and a quick look at the debate in the UK and
elsewhere made it look like they would be banned sooner rather than later.

Not a lot we do at the space is generally safe, but I personally try and
reduce the number of chemicals I inhale - nobody really knows what is in
the unregulated chemicals that people put in their Vaping machines - at
least when I am using solvents I can take appropriate precautions. When
people are Vaping around others, they remove that choice from people.

**Comment by Ravepants** [comment]
There is a lot of speculation about vaping at the moment, and as it currently stands with regards to the law and in industry, it is a matter of management preference.
I have worked in places that allow vaping while in the office and at your desk, and I currently work where you have to go outside. 
This has also caused issues due to some places needing vaping and traditional analogue smoking areas at opposite ends of the premises, as vapers don't generally want to be with smokers, after all the personal choice of vaping is to get away from the very harmful aspects of traditional smoking.
A recent 2 year study by the NHS has also deemed vaping to be at least 95% safer to the user than traditional smoking, and a 2 year study in the US recently has found that there is actually zero harm from passive vaping, yes you can still smell and see the vapour, but the users lungs have filtered out 90% of anything harmful to bystanders. 
This being said, I am still happy to go outside as being a traditional smoker previously, I understand that some people don't like it, and seeing most are in favour of the "safe space"  malarkey, then I'm happy to go along with that too.

**Comment by RussellHHH** [comment]
"Proving" smoking tobacco was even harmful to a smokers health took many many years! The case against second hand smoke has taken much longer.  Even so, the smoking ban is not stopping anyone smoking, just stopped people inflicting it on others.

I dislike vaping into the air that I breath. 

The mixtures put into vaping liquids are unregulated, so the effects will never be proved as anyone can say "oh, mine is one of the good ones"

"Banning on the basis of "Has not been proven to be harmful but it might be" seems a step beyond reasonableness to me, and rules based on unreason invite poor adherence."

**Comment by RussellHHH** [comment]
Damn sent that before finished editing!

**Comment by rlp10** [comment]
James, thank you for referencing the Guardian article, but I don't think that it supports the summary that you give. This recent study showed harmful effects on mice when exposed to e-cigarette fumes, and concluded that the effect of e-cigarettes on lungs was "not neutral". It makes no direct reference to the effect on humans further than suggesting the possibility of harm and therefore the need for further study. There is no mention or suggestion of harm through passive vaping. Perhaps a better summary would be: "There is no evidence that vaping is bad and it will help people give up smoking."

If there is widespread popular support amongst members for banning vaping on grounds of comfort/dislike, then I would suggest that it was best expressed by a vote at an AGM or the like. There will be people with strong feelings on both sides and a vote would be the only way to be sure which party, if either, had the majority.

I am not sure that framing the issue in terms of an infringement of personal liberty takes matters forwards. Isn't there freedoms and infringement of choice on both sides? I do not see that the non-vapers have a monopoly on that issue.

For the avoidance of doubt, I am not criticising the original inclusion of the rule in the draft. I am sure the trustees (and others?) have worked very hard to come up with this improved set of rules, a project which I consider to be very important. I am only now commenting in the hopes of furthering the consultation.

**Comment by Ravepants** [comment]
Also, the primary concern chemical wise at the moment is with the diacetyl used in some flavourings causing popcorn lung, but most well informed vapours will avoid any liquids with this in, and with stronger regulation coming in once the tpd is implemented in 2016 this will then become a banned substance, so that removes all potentially harmful chemicals, as propylene clycol and vegetable glycerine are inert chemicals, and you actually eat them a lot in food products, and have inhaled them if you've ever been at a disco or Rave using smoke machines, as it exactly the same principal vaping uses.

**Comment by rlp10** [comment]
Russell, you say that you dislike vaping in the air that you breathe. Some people like vaping in the space. On the issue of like/dislike, would you consider a vote to be a fair way of settling the matter?

You also point to the requirement of "proof" perhaps taking many years. I think you're setting the hurdle quite high. At this stage, I can't see any substantive evidence.

**Comment by rlp10** [comment]
Ravepants, could you reference the study/studies that you refer to, or an article or summary of them?

**Comment by geeksareforlife** [comment]
Sorry, I'm not trying to shut down the debate at all, this is exactly what
the consultation is for!

If the rules are completely changed at the end I will be a happy man.

All of my points about Vaping are my personal viewpoint - I should have
made that clearer. The only points I made as a trustee were around the
technicalities of how we discuss.

Thank you for starting a discussion, the trustees were starting to worry it
would never happen!

J

**Comment by RussellHHH** [comment]
Reasonable is not doing something that people find distasteful, obnoxious or offensive.

Unfortunately, as previously with smoking, most people who vape never consider asking if what they are doing offends the people they are with. Vaping or not vaping is a choice. I don't want to be forced into accepting second hand vaping, whatever they may contain.

**Comment by drazziweht** [comment]
Having spent some time looking for research on harm of vaping both primary and secondary my personal take is that at present there is an increasing consensus that secondary vaping is not at all harmful and primary vaping is at worst 90% less harmful than cigarettes.  

There is not yet definitive evidence of no harm from secondary vaping but there does seem to be a growing consensus that the upper bound on any possible harm is like to be below the threshold of detectability with current methods.

At least for me this put's the debate into the ream of member preferences rather than safety or objective harm reduction.

Given this I would add my support to those that think a membership vote on this rule would be the right way forward.

**Comment by rlp10** [comment]
> Reasonable is not doing something that people find distasteful, obnoxious or offensive.

"Reasonable" means "having sound judgement; fair and sensible" or "as much as is appropriate or fair; moderate". http://www.oxforddictionaries.com/definition/english/reasonable In my view, many things which are reasonable may also be distasteful, obnoxious or offensive.

I think your overall point however is that since some people find vaping distasteful, the respectful thing would be for no-one to vape. My position on this point remains that if it is a matter of taste/comfort, then it makes sense to sample the wishes of the membership through a vote.

**Comment by Ravepants** [comment]
For reference, the links to articles i mentioned:

Passive vaping:
http://www.ecigarettedirect.co.uk/ashtray-blog/2012/08/passive-vaping.html
http://www.ecigarettedirect.co.uk/ashtray-blog/2012/08/passive-vaping-causes-no-harm.html

90-95% less harmful than traditional smoking:
http://www.nhs.uk/news/2015/08August/Pages/E-cigarettes-95-per-cent-less-harmful-than-smoking-says-report.aspx
https://www.gov.uk/government/news/e-cigarettes-around-95-less-harmful-than-tobacco-estimates-landmark-review

My previous comment still stands, I haven't yet vaped in the space, but would if allowed, I would also go outside if it's what the majority want, we are a democracy after all.

**Comment by msemtd** [comment]
For the first article the conclusions seem to have been cherry-picked from the study (https://www.researchgate.net/publication/230615037_Acute_effects_of_electronic_and_tobacco_cigarette_smoking_on_complete_blood_count) and it is as expected: "Nevertheless, it is important to underline that the present results apply to the specific e-cigarette device and liquid tested and may not be reproducible in other devices and/or liquids. Moreover, the present results should be further confirmed by assessing the response of the main proteins of acute inflammatory load to the e-cigarette vapor." - I need some time to read it (and its references) properly

**Comment by msemtd** [comment]
I think the second article just references the first - it's links to the study and in-dept analysis can't be read. Dubious and hardly impartial! Let's have some better sources to look at.

**Comment by Ravepants** [comment]
http://www.ecigarette-research.com/web/index.php/2013-04-07-09-50-07/2014/184-passive-vape

its hard to find entirely impartial studies that aren't paywalled!

**Comment by drazziweht** [comment]
" the big tobacco companies stifling and producing contrary research data, however there are no big "vaping" companies to skew the results,"

There are however still big tobacco companies to skew the results away from vaping to retain cigarette sales. This is apparently happening, so be careful of "Independant" research, there are deep pockets with an interest in banning vaping.

**Comment by RussellHHH** [comment]
Tobacco links to Vaping

ecigarette-research.com/video6.htm

**Comment by RussellHHH** [comment]
Sorry that should be

https://www.YouTube.com/watch?v=lxpQWrocrkQ

**Comment by MartinTebb** [comment]
I have to say that since there is really no evidence of second hand harm (rather reasonable evidence to the contrary), simply banning it based on the personal opinion of a few members seems unreasonable. If there is a sufficient body of the membership that wants the ban based on personal preference, then I would say the option of a vote seems the most reasonable.

I'm sure there are members who dislike people playing music in the space, but there is no outright ban on that. It is simply left to people to sort it out among themselves, vaping should (in my opinion) be left the same.

**Comment by drazziweht** [comment]
"I'm sure there are members who dislike people playing music in the space, but there is no outright ban on that."

A good point, perhaps there should be, at very least banjo's which are a tool of the devil himself should certainly be beyond what any reasonable person would be expected to endure......

Tolerance, I've heard of it, didn't think much of the concept.

**Comment by Aeisharat** [comment]
Hi all, 
While I appreciate this is a hot topic, if we could not devolve to strawman arguments and rhetoric that would be much better. 

The reason for the consultation is measured discussion and debate to improve the space as a whole, and for those like me who are on the fence on the logistics of vaping in the space, I'd rather see a good sensible agreement than straw arguments and shenanigans.

**Comment by MartinTebb** [comment]
I would respectfully disagree with it being a straw man argument, my point with referencing music was simply one of precedent. If the health concerns are referenced as invalid/unfounded, then it becomes a discussion on the volume of people who dislike the aesthetics (including smell) of something required to ban it.  As such how the space has dealt with similar concerns in the past becomes directly relevant.

If Vaping is band simply due to a number of people who dislike/disapprove of it, then in fairness the same principle must be applied to other things. I am vegetarian, I find the smell of bacon almost sickening. Is it really taking things to an extreme to draw a comparison between the two? (It would be getting into straw man territory to declare I worry about meat eaters farting giving me mad cow)

**Comment by drazziweht** [comment]
"straw arguments and shenanigans"

Spoilsport !!.

I think the issue for me is that there is effectively no evidence for third party (passive vapeing) harm and very little evidence even for direct harm.

You could try searching primary references (I have) and found very little but I think a fairly compelling argument for the lack of harm is that both the WHO and BMA are very much in favour of a ban on vaping in public spaces.

Obviously as organisations the WHO and BMA are well placed to be able to locate and reference any evidence in favour of there stance, and yet neither have done so in any credible way.
I think if such evidence existed that the combined ability of these organisations would be able to point us to it and there apparent lack of ability to do so almost certainly indicates a lack of such evidence.

Without evidence it is not actually possible to have anything other than an opinion on the matter, and the forming of opinions without evidence is more about appeal to emotion and style than substance.

It's difficult to argue from the facts when there are no actual facts, hence why a vote is likely the only reasonable way to decide,

A vote of course is like an election, it needs a campaign, and a campaign is usually more emotional/political than logical.

**Comment by geeksareforlife** [comment]
I've got looked at the BMA, but the WHO has quite a few sources in its
research:

http://www.who.int/nmh/events/2014/backgrounder-e-cigarettes/en/

Pages 4 and 5 particularly

J

**Comment by drazziweht** [comment]
"I've got looked at the BMA, but the WHO has quite a few sources in its
research:"

This contains a number of references where vaping "May" cause some harm to the user
but less than smoking.

Also a number of references where high concentrations of substances and particle sizes used in vapeing can cause health issues and the fact that 'detectable; levels of some of these can be found in some passive use situations.

There is then an implied link between the two separate situations used to imply a possibility of harm from passive vaping, no evidence is given for this step at all.

The way the issues are conflated almost makes you think they want to confuse the issue.

At best the only conclusion you can come to from this document is that there is a possibility of harm from passive vaping. This sounds like a good reason for a ban until you actually realise there is a possibility of harm from almost any activity in the world, and of course a possibility of harm from no activity at all.

The problem here is that there is no way to prove total lack of harm, the WHO therefore comes down on the side of a cautionary ban. 

This is an opinion, my opinion is that you need at least some evidence of harm to justify banning something.

Otherwise anything with a possibility of harm would attract a ban, **WARNING STRAWMAN:**  It is not possible to prove that exposure to banjo music cannot cause mental instability in later life....

A number of other studies exist. Many of them are referenced from the link below with links to the original research.

http://www.ecigarettedirect.co.uk/ashtray-blog/2015/11/junk-e-cigarette-studies.html

**Comment by MartinTebb** [comment]
That's an interesting report, it brings up some good points. I would say that the only things found in second hand smoke in the primary literature (http://www.sciencedirect.com/science/article/pii/S1438463913001533) were the 1,2-propanediol, nicotine and bits and bobs like aluminium. While the health concerns of these things are being investigated, the levels in the exhaled vapour are really far lower than expelled from other common items (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2956675/).  They only found much in the way of symptoms from far more long term exposure than would be present in the space to higher levels than found in the first reference.

In summery, while some of the chemicals in the exhaled vapour are being investigated. The quantity added by the occasional vaper is not anywhere near the levels added by many other things within the space.

**Comment by geeksareforlife** [comment]
But isn't that really the point?

There is nothing in the space that expels nicotine, and would prefer to
keep this addictive substance that has proven health risks out of my body
as much as possible.

I don't smoke, or do drugs, or even consume caffeine. I occasionally drink
alcohol, but haven't been drunk in many years. It should be in choice what
chemicals go into my body, and Vaping in the space takes that choice away
from me.

Generally we try as hard as we can to separate things that could expel
horrible things - the spray booth, dusty area, etc - personally I think
this should be the same

**Comment by drazziweht** [comment]
geekareforlife said 
"I don't smoke, or do drugs, or even consume caffeine. I occasionally drink
alcohol, but haven't been drunk in many years. It should be in choice what
chemicals go into my body, and Vaping in the space takes that choice away
from me."

We are looking at nanogram levels at the top end of the range for passive absorption of nicotine from vapers in the space.

At these levels any effect is in the range of homoeopathic dosage and like homoeopathy is more in the realms of belief and opinion than fact or science as presently understood.

Adding additional rules can be from 2 standpoints that have some rational backing
1. There is evidence of harm caused
2. There is a personal preference.

My opinion is that in case #1 a ban is appropriate unless good reason for the activity can be shown in which case take steps to minimise harm.

Case #2 where there is a personal preference/opinion/belief but no evidence of harm should be a decision by majority as I can see no other rational way to make it.

I think vaping falls into case #2

Other than a vote on this how else could we decide on the rule ?

Strength of arms ?
Loudest voice ?
Most persistent poster ?
Best anecdote ?

**Comment by geeksareforlife** [comment]
I disagree on your points - I think there is more than enough evidence of
the existence of these products, but will happily say that there may not be
enough evidence yet of caused harm.

But yes, I am fine with a vote if we can't come to a conclusion here.

**Comment by Ravepants** [comment]
I'm sure vapers would be happy to vape in the fume extractor cabinet!
/joke. :-)

**Comment by MartinTebb** [comment]
While it is true that nicotine is expelled by e-cigs and is not in the air via anything other than smoking, the amount put out by a person vaping really is totally negligible. As far as the evidence already linked, there is nothing near the amount to course any actual effects. Nicotine itself is actually likely to be beneficial (link I have to hand, might have to google primary literature http://discovermagazine.com/2014/march/13-nicotine-fix) I very much appreciate individual rights to decide what goes into your own body, the issue of air purity is a very hard one however as controlling what is in the air requires the infringement of others freedom of choice. In reality the toxins from being near a road dwarf even the worst case potential for harm from vaping by quite a way.

**Comment by geeksareforlife** [comment]
Again, I will admit that the science in this is still new and up for
debate, but you are presenting this as if it is clear cut - it is not.

Just a few minutes of googling gives this:

http://www.fhi.no/dokumenter/136f741b1e.pdf

From the Norwegian Institute of Public Health.

The stuff I am interested in is at the bottom of page 3:

"The present data suggest that nicotine levels in the environment following
passive exposure to e-cigarette aerosols causes similarly high nicotine
levels in the blood as that of passive smoking of regular cigarettes."

Anything but homeopathic. That is only one study, but it looks a lot like
history repeating itself as people were forced to second hand smoke whilst
people debated the science.

**Comment by MartinTebb** [comment]
I would agree that the only fair way of settling this would seem to be a vote. Both sides of the argument seem to have been put forward rationally, and having all reviewed the evidence there is a difference of opinion that looks like it will remain. I would say at this stage should we continue we will simply get into a "I think it is this" and "I think it is that" discussion, rehashing the points already made.

**Comment by MartinTebb** [comment]
Oh, my apologies. I forgot to reference my comment on traffic fumes. http://www.ehhi.org/reports/exhaust/index.shtml

**Comment by msemtd** [comment]
We have no control over the traffic fumes that enter the hackspace and we are not trying to control those fumes but if we were then we would ask our trafficiking members to kindly not rev their engines in our shared air.

**Comment by MartinTebb** [comment]
Sorry I wasn't very clear with my point. I was not mentioning traffic fumes as a "well we don't block these" sort of argument, simply as a easily understandable reference point for common airborne chemicals.

**Comment by rlp10** [comment]
Unless there are further substantive comments then, I propose that this pull request is committed - removing the vaping prohibition until such time as a vote has been called by arranged by the trustees whether at an AGM or otherwise.

**Comment by loriamor** [comment]
I have read through the arguments and it seems to be the following and I would like to clarify that my point of bringing up the smell is not due to the fact that I dislike it - it is my concern that because I can smell it and I am sure that you cannot guarantee the vapor that is exhaled is 100% without nicotine or other chemicals that I do not wish to inhale - I would prefer vaping to be banned. 

Against vaping in the space - real or perceived risk to health. 

For vaping in the space - real or perceived risk to convenience. 

It is my opinion that health risk - either real or perceived risk is more important than being more convenient for a few people in the space.

**Comment by drazziweht** [comment]
The problem with this argument is that it applies equally to any made up 
risk if it is applied without evidence.

Ban Coffee in the space
I have read through the arguments and it seems to be the following and I 
would like to clarify that my point of bringing up the smell is not due 
to the fact that I dislike it - it is my concern that because I can 
smell it and I am sure that you cannot guarantee the vapor that is 
exhaled is 100% without caffine or other chemicals that I do not wish to 
inhale - I would prefer coffee to be banned.

Against coffee in the space - real or perceived risk to health.

For coffee in the space - real or perceived risk to convenience.

It is my opinion that health risk - either real or perceived risk is 
more important than being more convenient for a few people in the space.

........


------ Original Message ------

**Comment by loriamor** [comment]
The problem with that is that whilst a person may have some coffee breath after drinking coffee they do not then breath out huge plumes of coffee after drinking it as I have seen with vaping. You would have to get closer to them. So no, it is not really the same.

**Comment by drazziweht** [comment]
Do you have definitive evidence of the absolute safe levels of caffeine 
that will guarantee no danger from passive intake ?
Can you prove that there is no danger ?
If you cannot it is simply an opinion that caffine is safe and vaping is 
not .




------ Original Message ------

**Comment by geeksareforlife** [comment]
Caffeine is not safe, as even a small amount consumed by me results in
measurable changes to my mental and health state.

Coffee does not have caffeine in its "vapors". It is also a known product
with a known preparation method so these things can be measured and
guaranteed.

And I think we all agreed early on that strawmen were not welcome.

**Comment by drazziweht** [comment]
So how about caffeine vaping ?

http://www.techinsider.io/what-is-caffeine-vaping-2015-7

Is that presumed to be included in nicotine vaping or a seperate issue ?

**Comment by rlp10** [comment]
I agree, Lori, that health risk issues should generally receive greater
weight than considerations of convenience or comfort. Your point is well
made.

However, I don't think the former should automatically dictate policy no
matter how slight the health risk.

A counterexample, it seems to me, is that there is an undeniable
health/safety risk, if slight, to drinking in the space. There is plenty of
dangerous machinery around and in such a workshop in an employment
environment I have no doubt drink would be banned. However, on the whole,
people like drinking and so alcohol is not prohibited. It is an example of
prioritising convenience over health.

**Comment by daniel1111** [comment]
I think it's becoming clear that the only way this is going to be settled is if we arrange a vote 

Daniel

**Comment by geeksareforlife** [comment]
I didn't even realise that existed!

I wouldn't want it in the space, for exactly the same reasons.

**Comment by geeksareforlife** [comment]
You make a good point Richard, I think a specific note on rule 0 banning
the use of tools after drinking would be a good idea.

**Comment by drazziweht** [comment]
"I didn't even realise that existed"

Nor did I until I went looking for "Proof" that coffee vapour could be 
harmful !
I also found a study that showed aroma from coffee beans had a medical 
effect on sleep deprived rats
and some research that showed there were over 900 aromatic chemicals in 
vapour given off by hot coffee.

Things are never clear cut when you have a gas chromatograph able to get 
close to measuring single molecules diluted in air.

Chris



------ Original Message ------

**Comment by geeksareforlife** [comment]
I have to agree with Daniel in this - the trustees will call a vote in the
new year.

I would suggest that until then we let this topic rest.

If anyone wants to contribute anything *new* then please do, but let's not
rehash old arguments for now.

J

**Comment by drazziweht** [comment]
"You make a good point Richard, I think a specific note on rule 0 
banning
the use of tools after drinking would be a good idea."

Noooo Please, let us not get carried away with rule making.

The Hackspace by definition is a place with dangerous machines in it
It cannot work without the membership exercising common sense.

The rules are there to allow us to castigate those with no common sense, 
not to prescribe every aspect of there life.

How much can you drink before operating the Tig Welder ?
Is it more or less for the Bridgeport Mill ?
What about a screwdriver ?
Or the Table Saw ?

What about drinking before arriving at the hackspace ?

Do we need a rule about hacking while tiered , this can also be 
dangerous, how about a rule limiting the hours of continuous hacking
allowed ?

If we go down the route of trying to have rules for everything 99% of 
the rules will be ignored, nobody will read or respect the rules, the 
trustees will need enforcers/judges etc to keep the rules.

It's the wrong way to go, we should be looking at which rules we can 
remove, not which extra rules we should add.

Chris




------ Original Message ------

**Comment by geeksareforlife** [comment]
Sorry, I didn't make it clear that I was being silly - my opinion is that
rule 0 already covers this.

However, I disagree with your general point - as we get larger, rules
become more important. I agree that they should be as little as possible,
but I disagree that the membership as a whole as common sense, and the
rules are there to plug the gap.

**Comment by MartinTebb** [comment]
I agree the space gets larger more rules become necessary. It is very easy to assume everyone approaches things from the same grounding in common sense you try to, from experience this is very much not the case. Different people have very different ideas of what is appropriate and safe. I would never consider driving drunk, but many people think it is perfectly acceptable to. I haven't seen anyone drunkenly trying to lick the arc welder though, so in this case people probably have enough sense.

**Comment by jamesfowkes** [comment]
People drink-drive in spite of a law against it, not because of the absence of one.

Banning something doesn't necessarily stop it happening.

**Comment by MartinTebb** [comment]
I have to say not implementing a rule simply because some people might not follow it doesn't seem to be very sound reasoning. To continue the analogy, the incidents of drink driving went down drastically once the law was in place.

**Comment by rlp10** [comment]
James, I also misunderstood your suggestion for Rule 0. Sorry, my sarcasm radar is obviously insufficiently sensitive!

**Comment by drazziweht** [comment]
"I have to say not implementing a rule simply because some people might not follow it doesn't seem to be very sound reasoning. To continue the analogy, the incidents of drink driving went down drastically once the law was in place."

We have a problem getting people to engage, for example only about 20% of the membership are on the google group and only about 20 members are looking at the rules discussion.

Would a rule mandating engagement be useful ?

I guess the point is that you should not implement rules that you are not willing/able to enforce.

**Comment by CongoJoe** [comment]
I'd like to add some specific experience on this topic. 

When vaping first became popular, a smoker I share an office with asked if we mind him vaping inside. 

We agreed as long as he used and e-pipe, because it makes him seem more intelligent. 

Apart from a sweet smell, it didn't cause us any problems and puntuating sentences with a puff on the pipe really made him seem classy :-)

However... Not all vapers are equal. 

He has now moved onto a massively more powerful machine and much stronger concentrations of liquid. 
The plumes of vapour this thing puts out gives me a quite strong nicotine rush and after a while becomes unbearable. 

He now no longer vapes in the office. 

I imagine most studies on second hand vape focus on popular brands rather than the over volted "cloud chasing" machines. 

If the concentration of nicotine is high enough to make me feel unwell via second hand smoke, then the concentration of whatever other chemicals are in there will also be significant.

**Comment by geeksareforlife** [comment]
A vote has taken taken place, with all current members (359) eligble to vote. of the 186 that did vote, 135 voted to not allow vaping in the space.  This PR is therefore closed without merging.

image

**Pull request closed without merging**
